"""add document storage path

Revision ID: 87f4679eca77
Revises: 16c517d8c41d
Create Date: 2026-09-12 17:51:45.189581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f4679eca77'
down_revision: Union[str, Sequence[str], None] = '16c517d8c41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_path', sa.String(), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'storage_path')
    # ### end Alembic commands ###
