"""add document processing attempts

Revision ID: de557f7c80c5
Revises: 87f4679eca77
Create Date: 2026-09-13 22:54:40.769162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de557f7c80c5'
down_revision: Union[str, Sequence[str], None] = '87f4679eca77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_attempts')
    # ### end Alembic commands ###
